FROM openjdk:12-jdk-alpine
LABEL maintainer="qhgml100@naver.com"
ARG APP_VERSION=1.0
RUN apk update && apk add curl
WORKDIR /App/springbootsampleapp
COPY build/libs/pay-spring-boot-sample-web-ui-${APP_VERSION}.war /App/springbootsampleapp/spring-boot-sample.war
EXPOSE 8080
CMD ["sh","-c","java -jar spring-boot-sample.war"]
